export const INITIALIZE_APP = 'INITIALIZE_APP';
export const INITIALIZE_APP_COMPLETED = 'INITIALIZE_APP_COMPLETED';
export const INITIALIZE_APP_FAILED = 'INITIALIZE_APP_FAILED';
export const UPDATE_CURRENT_LOCATION = 'UPDATE_CURRENT_LOCATION';
export const UPDATE_CURRENT_LOCATION_COMPLETED = 'UPDATE_CURRENT_LOCATION_COMPLETED';

// Group
export const SEARCH_GROUP = 'SEARCH_GROUP';
export const SEARCH_GROUP_COMPLETED = 'SEARCH_GROUP_COMPLETED';
export const CREATE_GROUP = 'CREATE_GROUP';
export const CREATE_GROUP_COMPLETED = 'CREATE_GROUP_COMPLETED';
export const WATCHING_GROUP = 'WATCHING_GROUP';

// Profile
export const CHANGE_PROFILE_NAME = 'CHANGE_PROFILE_NAME';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

// Location
export const WATCHING_LOCATION = 'WATCHING_LOCATION';
export const STOP_WATCHING_LOCATION = 'STOP_WATCHING_LOCATION';
